/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MixingRouteImport } from './routes/mixing'
import { Route as AiInfluencerRouteImport } from './routes/ai-influencer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInfluencerIndexRouteImport } from './routes/ai-influencer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SystemSettingsRouteImport } from './routes/system.settings'
import { Route as SystemHelpRouteImport } from './routes/system.help'
import { Route as SystemAnalyticRouteImport } from './routes/system.analytic'
import { Route as MixingDubbingRouteImport } from './routes/mixing.dubbing'
import { Route as MixingClipperRouteImport } from './routes/mixing.clipper'
import { Route as ManageTokensRouteImport } from './routes/manage.tokens'
import { Route as ManageRoutingRouteImport } from './routes/manage.routing'
import { Route as GenerateStoryboardRouteImport } from './routes/generate.storyboard'
import { Route as GenerateNaratifRouteImport } from './routes/generate.naratif'
import { Route as GenerateMotionRouteImport } from './routes/generate.motion'
import { Route as GenerateImageToVideoRouteImport } from './routes/generate.image-to-video'
import { Route as GenerateBulkFashionRouteImport } from './routes/generate.bulk-fashion'
import { Route as DevWeavyTestRouteImport } from './routes/dev.weavy-test'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy-image'
import { Route as AiInfluencerPublisherRouteImport } from './routes/ai-influencer.publisher'
import { Route as AiInfluencerPlannerRouteImport } from './routes/ai-influencer.planner'
import { Route as AiInfluencerLibraryRouteImport } from './routes/ai-influencer.library'
import { Route as AiInfluencerCharacterRouteImport } from './routes/ai-influencer.character'
import { Route as AiInfluencerBrainRouteImport } from './routes/ai-influencer.brain'
import { Route as AiInfluencerAnalyticsRouteImport } from './routes/ai-influencer.analytics'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTokenBankRouteImport } from './routes/admin.token-bank'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as ApiRouterVoiceRouteImport } from './routes/api/router/voice'
import { Route as ApiRouterVideoRouteImport } from './routes/api/router/video'
import { Route as ApiRouterSubtitleRouteImport } from './routes/api/router/subtitle'
import { Route as ApiRouterSttRouteImport } from './routes/api/router/stt'
import { Route as ApiRouterRenderCloudRouteImport } from './routes/api/router/render-cloud'
import { Route as ApiRouterRenderRouteImport } from './routes/api/router/render'
import { Route as ApiRouterPlanWeeklyRouteImport } from './routes/api/router/plan-weekly'
import { Route as ApiRouterImageRouteImport } from './routes/api/router/image'
import { Route as ApiRouterChatRouteImport } from './routes/api/router/chat'
import { Route as ApiRouterBrainAnalyzeRouteImport } from './routes/api/router/brain-analyze'
import { Route as ApiPublicUploadCatboxRouteImport } from './routes/api/public/upload-catbox'
import { Route as ApiPublicStoryboardBrainRouteImport } from './routes/api/public/storyboard-brain'
import { Route as ApiPublicScrapeProductRouteImport } from './routes/api/public/scrape-product'
import { Route as ApiPublicScrapeArticleRouteImport } from './routes/api/public/scrape-article'
import { Route as ApiPublicProxyImageRouteImport } from './routes/api/public/proxy-image'
import { Route as ApiPublicNaratifBrainRouteImport } from './routes/api/public/naratif-brain'
import { Route as ApiPublicMagnificRouteImport } from './routes/api/public/magnific'
import { Route as ApiPublicFfmpegCdnRouteImport } from './routes/api/public/ffmpeg-cdn'
import { Route as ApiPublicElevenlabsValidateRouteImport } from './routes/api/public/elevenlabs-validate'
import { Route as ApiPublicElevenlabsTtsRouteImport } from './routes/api/public/elevenlabs-tts'
import { Route as ApiPublicDubbingBrainRouteImport } from './routes/api/public/dubbing-brain'
import { Route as ApiPublicCreativeBrainRouteImport } from './routes/api/public/creative-brain'
import { Route as ApiPublicClipperBrainRouteImport } from './routes/api/public/clipper-brain'
import { Route as ApiPublicMidtransNotificationRouteImport } from './routes/api/public/midtrans/notification'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MixingRoute = MixingRouteImport.update({
  id: '/mixing',
  path: '/mixing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerRoute = AiInfluencerRouteImport.update({
  id: '/ai-influencer',
  path: '/ai-influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerIndexRoute = AiInfluencerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHelpRoute = SystemHelpRouteImport.update({
  id: '/system/help',
  path: '/system/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAnalyticRoute = SystemAnalyticRouteImport.update({
  id: '/system/analytic',
  path: '/system/analytic',
  getParentRoute: () => rootRouteImport,
} as any)
const MixingDubbingRoute = MixingDubbingRouteImport.update({
  id: '/dubbing',
  path: '/dubbing',
  getParentRoute: () => MixingRoute,
} as any)
const MixingClipperRoute = MixingClipperRouteImport.update({
  id: '/clipper',
  path: '/clipper',
  getParentRoute: () => MixingRoute,
} as any)
const ManageTokensRoute = ManageTokensRouteImport.update({
  id: '/manage/tokens',
  path: '/manage/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoutingRoute = ManageRoutingRouteImport.update({
  id: '/manage/routing',
  path: '/manage/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateStoryboardRoute = GenerateStoryboardRouteImport.update({
  id: '/generate/storyboard',
  path: '/generate/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateNaratifRoute = GenerateNaratifRouteImport.update({
  id: '/generate/naratif',
  path: '/generate/naratif',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateMotionRoute = GenerateMotionRouteImport.update({
  id: '/generate/motion',
  path: '/generate/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateImageToVideoRoute = GenerateImageToVideoRouteImport.update({
  id: '/generate/image-to-video',
  path: '/generate/image-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateBulkFashionRoute = GenerateBulkFashionRouteImport.update({
  id: '/generate/bulk-fashion',
  path: '/generate/bulk-fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWeavyTestRoute = DevWeavyTestRouteImport.update({
  id: '/dev/weavy-test',
  path: '/dev/weavy-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerPublisherRoute = AiInfluencerPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerPlannerRoute = AiInfluencerPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerLibraryRoute = AiInfluencerLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerCharacterRoute = AiInfluencerCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerBrainRoute = AiInfluencerBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerAnalyticsRoute = AiInfluencerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokenBankRoute = AdminTokenBankRouteImport.update({
  id: '/token-bank',
  path: '/token-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRouterVoiceRoute = ApiRouterVoiceRouteImport.update({
  id: '/api/router/voice',
  path: '/api/router/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterVideoRoute = ApiRouterVideoRouteImport.update({
  id: '/api/router/video',
  path: '/api/router/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterSubtitleRoute = ApiRouterSubtitleRouteImport.update({
  id: '/api/router/subtitle',
  path: '/api/router/subtitle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterSttRoute = ApiRouterSttRouteImport.update({
  id: '/api/router/stt',
  path: '/api/router/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterRenderCloudRoute = ApiRouterRenderCloudRouteImport.update({
  id: '/api/router/render-cloud',
  path: '/api/router/render-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterRenderRoute = ApiRouterRenderRouteImport.update({
  id: '/api/router/render',
  path: '/api/router/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterPlanWeeklyRoute = ApiRouterPlanWeeklyRouteImport.update({
  id: '/api/router/plan-weekly',
  path: '/api/router/plan-weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterImageRoute = ApiRouterImageRouteImport.update({
  id: '/api/router/image',
  path: '/api/router/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterChatRoute = ApiRouterChatRouteImport.update({
  id: '/api/router/chat',
  path: '/api/router/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterBrainAnalyzeRoute = ApiRouterBrainAnalyzeRouteImport.update({
  id: '/api/router/brain-analyze',
  path: '/api/router/brain-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadCatboxRoute = ApiPublicUploadCatboxRouteImport.update({
  id: '/api/public/upload-catbox',
  path: '/api/public/upload-catbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoryboardBrainRoute =
  ApiPublicStoryboardBrainRouteImport.update({
    id: '/api/public/storyboard-brain',
    path: '/api/public/storyboard-brain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScrapeProductRoute = ApiPublicScrapeProductRouteImport.update({
  id: '/api/public/scrape-product',
  path: '/api/public/scrape-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapeArticleRoute = ApiPublicScrapeArticleRouteImport.update({
  id: '/api/public/scrape-article',
  path: '/api/public/scrape-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyImageRoute = ApiPublicProxyImageRouteImport.update({
  id: '/api/public/proxy-image',
  path: '/api/public/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNaratifBrainRoute = ApiPublicNaratifBrainRouteImport.update({
  id: '/api/public/naratif-brain',
  path: '/api/public/naratif-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMagnificRoute = ApiPublicMagnificRouteImport.update({
  id: '/api/public/magnific',
  path: '/api/public/magnific',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFfmpegCdnRoute = ApiPublicFfmpegCdnRouteImport.update({
  id: '/api/public/ffmpeg-cdn',
  path: '/api/public/ffmpeg-cdn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsValidateRoute =
  ApiPublicElevenlabsValidateRouteImport.update({
    id: '/api/public/elevenlabs-validate',
    path: '/api/public/elevenlabs-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsTtsRoute = ApiPublicElevenlabsTtsRouteImport.update({
  id: '/api/public/elevenlabs-tts',
  path: '/api/public/elevenlabs-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDubbingBrainRoute = ApiPublicDubbingBrainRouteImport.update({
  id: '/api/public/dubbing-brain',
  path: '/api/public/dubbing-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreativeBrainRoute = ApiPublicCreativeBrainRouteImport.update({
  id: '/api/public/creative-brain',
  path: '/api/public/creative-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipperBrainRoute = ApiPublicClipperBrainRouteImport.update({
  id: '/api/public/clipper-brain',
  path: '/api/public/clipper-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMidtransNotificationRoute =
  ApiPublicMidtransNotificationRouteImport.update({
    id: '/api/public/midtrans/notification',
    path: '/api/public/midtrans/notification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-influencer': typeof AiInfluencerRouteWithChildren
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-influencer/': typeof AiInfluencerIndexRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/video': typeof ApiRouterVideoRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/ai-influencer': typeof AiInfluencerIndexRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/video': typeof ApiRouterVideoRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-influencer': typeof AiInfluencerRouteWithChildren
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-influencer/': typeof AiInfluencerIndexRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/video': typeof ApiRouterVideoRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-influencer'
    | '/mixing'
    | '/profile'
    | '/admin/access'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/image-to-video'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/system/analytic'
    | '/system/help'
    | '/system/settings'
    | '/admin/'
    | '/ai-influencer/'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/proxy-image'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/video'
    | '/api/router/voice'
    | '/api/public/midtrans/notification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mixing'
    | '/profile'
    | '/admin/access'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/image-to-video'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/system/analytic'
    | '/system/help'
    | '/system/settings'
    | '/admin'
    | '/ai-influencer'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/proxy-image'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/video'
    | '/api/router/voice'
    | '/api/public/midtrans/notification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-influencer'
    | '/mixing'
    | '/profile'
    | '/admin/access'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/image-to-video'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/system/analytic'
    | '/system/help'
    | '/system/settings'
    | '/admin/'
    | '/ai-influencer/'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/proxy-image'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/video'
    | '/api/router/voice'
    | '/api/public/midtrans/notification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiInfluencerRoute: typeof AiInfluencerRouteWithChildren
  MixingRoute: typeof MixingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevWeavyTestRoute: typeof DevWeavyTestRoute
  GenerateBulkFashionRoute: typeof GenerateBulkFashionRoute
  GenerateImageToVideoRoute: typeof GenerateImageToVideoRoute
  GenerateMotionRoute: typeof GenerateMotionRoute
  GenerateNaratifRoute: typeof GenerateNaratifRoute
  GenerateStoryboardRoute: typeof GenerateStoryboardRoute
  ManageRoutingRoute: typeof ManageRoutingRoute
  ManageTokensRoute: typeof ManageTokensRoute
  SystemAnalyticRoute: typeof SystemAnalyticRoute
  SystemHelpRoute: typeof SystemHelpRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  ApiPublicClipperBrainRoute: typeof ApiPublicClipperBrainRoute
  ApiPublicCreativeBrainRoute: typeof ApiPublicCreativeBrainRoute
  ApiPublicDubbingBrainRoute: typeof ApiPublicDubbingBrainRoute
  ApiPublicElevenlabsTtsRoute: typeof ApiPublicElevenlabsTtsRoute
  ApiPublicElevenlabsValidateRoute: typeof ApiPublicElevenlabsValidateRoute
  ApiPublicFfmpegCdnRoute: typeof ApiPublicFfmpegCdnRoute
  ApiPublicMagnificRoute: typeof ApiPublicMagnificRoute
  ApiPublicNaratifBrainRoute: typeof ApiPublicNaratifBrainRoute
  ApiPublicProxyImageRoute: typeof ApiPublicProxyImageRoute
  ApiPublicScrapeArticleRoute: typeof ApiPublicScrapeArticleRoute
  ApiPublicScrapeProductRoute: typeof ApiPublicScrapeProductRoute
  ApiPublicStoryboardBrainRoute: typeof ApiPublicStoryboardBrainRoute
  ApiPublicUploadCatboxRoute: typeof ApiPublicUploadCatboxRoute
  ApiRouterBrainAnalyzeRoute: typeof ApiRouterBrainAnalyzeRoute
  ApiRouterChatRoute: typeof ApiRouterChatRoute
  ApiRouterImageRoute: typeof ApiRouterImageRoute
  ApiRouterPlanWeeklyRoute: typeof ApiRouterPlanWeeklyRoute
  ApiRouterRenderRoute: typeof ApiRouterRenderRoute
  ApiRouterRenderCloudRoute: typeof ApiRouterRenderCloudRoute
  ApiRouterSttRoute: typeof ApiRouterSttRoute
  ApiRouterSubtitleRoute: typeof ApiRouterSubtitleRoute
  ApiRouterVideoRoute: typeof ApiRouterVideoRoute
  ApiRouterVoiceRoute: typeof ApiRouterVoiceRoute
  ApiPublicMidtransNotificationRoute: typeof ApiPublicMidtransNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixing': {
      id: '/mixing'
      path: '/mixing'
      fullPath: '/mixing'
      preLoaderRoute: typeof MixingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer': {
      id: '/ai-influencer'
      path: '/ai-influencer'
      fullPath: '/ai-influencer'
      preLoaderRoute: typeof AiInfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer/': {
      id: '/ai-influencer/'
      path: '/'
      fullPath: '/ai-influencer/'
      preLoaderRoute: typeof AiInfluencerIndexRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/help': {
      id: '/system/help'
      path: '/system/help'
      fullPath: '/system/help'
      preLoaderRoute: typeof SystemHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/analytic': {
      id: '/system/analytic'
      path: '/system/analytic'
      fullPath: '/system/analytic'
      preLoaderRoute: typeof SystemAnalyticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixing/dubbing': {
      id: '/mixing/dubbing'
      path: '/dubbing'
      fullPath: '/mixing/dubbing'
      preLoaderRoute: typeof MixingDubbingRouteImport
      parentRoute: typeof MixingRoute
    }
    '/mixing/clipper': {
      id: '/mixing/clipper'
      path: '/clipper'
      fullPath: '/mixing/clipper'
      preLoaderRoute: typeof MixingClipperRouteImport
      parentRoute: typeof MixingRoute
    }
    '/manage/tokens': {
      id: '/manage/tokens'
      path: '/manage/tokens'
      fullPath: '/manage/tokens'
      preLoaderRoute: typeof ManageTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/routing': {
      id: '/manage/routing'
      path: '/manage/routing'
      fullPath: '/manage/routing'
      preLoaderRoute: typeof ManageRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/storyboard': {
      id: '/generate/storyboard'
      path: '/generate/storyboard'
      fullPath: '/generate/storyboard'
      preLoaderRoute: typeof GenerateStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/naratif': {
      id: '/generate/naratif'
      path: '/generate/naratif'
      fullPath: '/generate/naratif'
      preLoaderRoute: typeof GenerateNaratifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/motion': {
      id: '/generate/motion'
      path: '/generate/motion'
      fullPath: '/generate/motion'
      preLoaderRoute: typeof GenerateMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/image-to-video': {
      id: '/generate/image-to-video'
      path: '/generate/image-to-video'
      fullPath: '/generate/image-to-video'
      preLoaderRoute: typeof GenerateImageToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/bulk-fashion': {
      id: '/generate/bulk-fashion'
      path: '/generate/bulk-fashion'
      fullPath: '/generate/bulk-fashion'
      preLoaderRoute: typeof GenerateBulkFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/weavy-test': {
      id: '/dev/weavy-test'
      path: '/dev/weavy-test'
      fullPath: '/dev/weavy-test'
      preLoaderRoute: typeof DevWeavyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer/publisher': {
      id: '/ai-influencer/publisher'
      path: '/publisher'
      fullPath: '/ai-influencer/publisher'
      preLoaderRoute: typeof AiInfluencerPublisherRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/planner': {
      id: '/ai-influencer/planner'
      path: '/planner'
      fullPath: '/ai-influencer/planner'
      preLoaderRoute: typeof AiInfluencerPlannerRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/library': {
      id: '/ai-influencer/library'
      path: '/library'
      fullPath: '/ai-influencer/library'
      preLoaderRoute: typeof AiInfluencerLibraryRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/character': {
      id: '/ai-influencer/character'
      path: '/character'
      fullPath: '/ai-influencer/character'
      preLoaderRoute: typeof AiInfluencerCharacterRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/brain': {
      id: '/ai-influencer/brain'
      path: '/brain'
      fullPath: '/ai-influencer/brain'
      preLoaderRoute: typeof AiInfluencerBrainRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/analytics': {
      id: '/ai-influencer/analytics'
      path: '/analytics'
      fullPath: '/ai-influencer/analytics'
      preLoaderRoute: typeof AiInfluencerAnalyticsRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/token-bank': {
      id: '/admin/token-bank'
      path: '/token-bank'
      fullPath: '/admin/token-bank'
      preLoaderRoute: typeof AdminTokenBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/router/voice': {
      id: '/api/router/voice'
      path: '/api/router/voice'
      fullPath: '/api/router/voice'
      preLoaderRoute: typeof ApiRouterVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/video': {
      id: '/api/router/video'
      path: '/api/router/video'
      fullPath: '/api/router/video'
      preLoaderRoute: typeof ApiRouterVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/subtitle': {
      id: '/api/router/subtitle'
      path: '/api/router/subtitle'
      fullPath: '/api/router/subtitle'
      preLoaderRoute: typeof ApiRouterSubtitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/stt': {
      id: '/api/router/stt'
      path: '/api/router/stt'
      fullPath: '/api/router/stt'
      preLoaderRoute: typeof ApiRouterSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/render-cloud': {
      id: '/api/router/render-cloud'
      path: '/api/router/render-cloud'
      fullPath: '/api/router/render-cloud'
      preLoaderRoute: typeof ApiRouterRenderCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/render': {
      id: '/api/router/render'
      path: '/api/router/render'
      fullPath: '/api/router/render'
      preLoaderRoute: typeof ApiRouterRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/plan-weekly': {
      id: '/api/router/plan-weekly'
      path: '/api/router/plan-weekly'
      fullPath: '/api/router/plan-weekly'
      preLoaderRoute: typeof ApiRouterPlanWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/image': {
      id: '/api/router/image'
      path: '/api/router/image'
      fullPath: '/api/router/image'
      preLoaderRoute: typeof ApiRouterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/chat': {
      id: '/api/router/chat'
      path: '/api/router/chat'
      fullPath: '/api/router/chat'
      preLoaderRoute: typeof ApiRouterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/brain-analyze': {
      id: '/api/router/brain-analyze'
      path: '/api/router/brain-analyze'
      fullPath: '/api/router/brain-analyze'
      preLoaderRoute: typeof ApiRouterBrainAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-catbox': {
      id: '/api/public/upload-catbox'
      path: '/api/public/upload-catbox'
      fullPath: '/api/public/upload-catbox'
      preLoaderRoute: typeof ApiPublicUploadCatboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/storyboard-brain': {
      id: '/api/public/storyboard-brain'
      path: '/api/public/storyboard-brain'
      fullPath: '/api/public/storyboard-brain'
      preLoaderRoute: typeof ApiPublicStoryboardBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape-product': {
      id: '/api/public/scrape-product'
      path: '/api/public/scrape-product'
      fullPath: '/api/public/scrape-product'
      preLoaderRoute: typeof ApiPublicScrapeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape-article': {
      id: '/api/public/scrape-article'
      path: '/api/public/scrape-article'
      fullPath: '/api/public/scrape-article'
      preLoaderRoute: typeof ApiPublicScrapeArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy-image': {
      id: '/api/public/proxy-image'
      path: '/api/public/proxy-image'
      fullPath: '/api/public/proxy-image'
      preLoaderRoute: typeof ApiPublicProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/naratif-brain': {
      id: '/api/public/naratif-brain'
      path: '/api/public/naratif-brain'
      fullPath: '/api/public/naratif-brain'
      preLoaderRoute: typeof ApiPublicNaratifBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/magnific': {
      id: '/api/public/magnific'
      path: '/api/public/magnific'
      fullPath: '/api/public/magnific'
      preLoaderRoute: typeof ApiPublicMagnificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ffmpeg-cdn': {
      id: '/api/public/ffmpeg-cdn'
      path: '/api/public/ffmpeg-cdn'
      fullPath: '/api/public/ffmpeg-cdn'
      preLoaderRoute: typeof ApiPublicFfmpegCdnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-validate': {
      id: '/api/public/elevenlabs-validate'
      path: '/api/public/elevenlabs-validate'
      fullPath: '/api/public/elevenlabs-validate'
      preLoaderRoute: typeof ApiPublicElevenlabsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-tts': {
      id: '/api/public/elevenlabs-tts'
      path: '/api/public/elevenlabs-tts'
      fullPath: '/api/public/elevenlabs-tts'
      preLoaderRoute: typeof ApiPublicElevenlabsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dubbing-brain': {
      id: '/api/public/dubbing-brain'
      path: '/api/public/dubbing-brain'
      fullPath: '/api/public/dubbing-brain'
      preLoaderRoute: typeof ApiPublicDubbingBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/creative-brain': {
      id: '/api/public/creative-brain'
      path: '/api/public/creative-brain'
      fullPath: '/api/public/creative-brain'
      preLoaderRoute: typeof ApiPublicCreativeBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clipper-brain': {
      id: '/api/public/clipper-brain'
      path: '/api/public/clipper-brain'
      fullPath: '/api/public/clipper-brain'
      preLoaderRoute: typeof ApiPublicClipperBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/midtrans/notification': {
      id: '/api/public/midtrans/notification'
      path: '/api/public/midtrans/notification'
      fullPath: '/api/public/midtrans/notification'
      preLoaderRoute: typeof ApiPublicMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTokenBankRoute: typeof AdminTokenBankRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTokenBankRoute: AdminTokenBankRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiInfluencerRouteChildren {
  AiInfluencerAnalyticsRoute: typeof AiInfluencerAnalyticsRoute
  AiInfluencerBrainRoute: typeof AiInfluencerBrainRoute
  AiInfluencerCharacterRoute: typeof AiInfluencerCharacterRoute
  AiInfluencerLibraryRoute: typeof AiInfluencerLibraryRoute
  AiInfluencerPlannerRoute: typeof AiInfluencerPlannerRoute
  AiInfluencerPublisherRoute: typeof AiInfluencerPublisherRoute
  AiInfluencerIndexRoute: typeof AiInfluencerIndexRoute
}

const AiInfluencerRouteChildren: AiInfluencerRouteChildren = {
  AiInfluencerAnalyticsRoute: AiInfluencerAnalyticsRoute,
  AiInfluencerBrainRoute: AiInfluencerBrainRoute,
  AiInfluencerCharacterRoute: AiInfluencerCharacterRoute,
  AiInfluencerLibraryRoute: AiInfluencerLibraryRoute,
  AiInfluencerPlannerRoute: AiInfluencerPlannerRoute,
  AiInfluencerPublisherRoute: AiInfluencerPublisherRoute,
  AiInfluencerIndexRoute: AiInfluencerIndexRoute,
}

const AiInfluencerRouteWithChildren = AiInfluencerRoute._addFileChildren(
  AiInfluencerRouteChildren,
)

interface MixingRouteChildren {
  MixingClipperRoute: typeof MixingClipperRoute
  MixingDubbingRoute: typeof MixingDubbingRoute
}

const MixingRouteChildren: MixingRouteChildren = {
  MixingClipperRoute: MixingClipperRoute,
  MixingDubbingRoute: MixingDubbingRoute,
}

const MixingRouteWithChildren =
  MixingRoute._addFileChildren(MixingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiInfluencerRoute: AiInfluencerRouteWithChildren,
  MixingRoute: MixingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevWeavyTestRoute: DevWeavyTestRoute,
  GenerateBulkFashionRoute: GenerateBulkFashionRoute,
  GenerateImageToVideoRoute: GenerateImageToVideoRoute,
  GenerateMotionRoute: GenerateMotionRoute,
  GenerateNaratifRoute: GenerateNaratifRoute,
  GenerateStoryboardRoute: GenerateStoryboardRoute,
  ManageRoutingRoute: ManageRoutingRoute,
  ManageTokensRoute: ManageTokensRoute,
  SystemAnalyticRoute: SystemAnalyticRoute,
  SystemHelpRoute: SystemHelpRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  ApiPublicClipperBrainRoute: ApiPublicClipperBrainRoute,
  ApiPublicCreativeBrainRoute: ApiPublicCreativeBrainRoute,
  ApiPublicDubbingBrainRoute: ApiPublicDubbingBrainRoute,
  ApiPublicElevenlabsTtsRoute: ApiPublicElevenlabsTtsRoute,
  ApiPublicElevenlabsValidateRoute: ApiPublicElevenlabsValidateRoute,
  ApiPublicFfmpegCdnRoute: ApiPublicFfmpegCdnRoute,
  ApiPublicMagnificRoute: ApiPublicMagnificRoute,
  ApiPublicNaratifBrainRoute: ApiPublicNaratifBrainRoute,
  ApiPublicProxyImageRoute: ApiPublicProxyImageRoute,
  ApiPublicScrapeArticleRoute: ApiPublicScrapeArticleRoute,
  ApiPublicScrapeProductRoute: ApiPublicScrapeProductRoute,
  ApiPublicStoryboardBrainRoute: ApiPublicStoryboardBrainRoute,
  ApiPublicUploadCatboxRoute: ApiPublicUploadCatboxRoute,
  ApiRouterBrainAnalyzeRoute: ApiRouterBrainAnalyzeRoute,
  ApiRouterChatRoute: ApiRouterChatRoute,
  ApiRouterImageRoute: ApiRouterImageRoute,
  ApiRouterPlanWeeklyRoute: ApiRouterPlanWeeklyRoute,
  ApiRouterRenderRoute: ApiRouterRenderRoute,
  ApiRouterRenderCloudRoute: ApiRouterRenderCloudRoute,
  ApiRouterSttRoute: ApiRouterSttRoute,
  ApiRouterSubtitleRoute: ApiRouterSubtitleRoute,
  ApiRouterVideoRoute: ApiRouterVideoRoute,
  ApiRouterVoiceRoute: ApiRouterVoiceRoute,
  ApiPublicMidtransNotificationRoute: ApiPublicMidtransNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
