/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReffEditRouteImport } from './routes/reff-edit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MixingRouteImport } from './routes/mixing'
import { Route as AiInfluencerRouteImport } from './routes/ai-influencer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInfluencerIndexRouteImport } from './routes/ai-influencer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SystemSettingsRouteImport } from './routes/system.settings'
import { Route as SystemHelpRouteImport } from './routes/system.help'
import { Route as SystemCloudRouteImport } from './routes/system.cloud'
import { Route as SystemAnalyticRouteImport } from './routes/system.analytic'
import { Route as ReffEditVideoRouteImport } from './routes/reff-edit.video'
import { Route as ReffEditImageRouteImport } from './routes/reff-edit.image'
import { Route as ReffEditHistoryRouteImport } from './routes/reff-edit.history'
import { Route as MixingDubbingRouteImport } from './routes/mixing.dubbing'
import { Route as MixingClipperRouteImport } from './routes/mixing.clipper'
import { Route as ManageTokensRouteImport } from './routes/manage.tokens'
import { Route as ManageRoutingRouteImport } from './routes/manage.routing'
import { Route as ManageAccountsRouteImport } from './routes/manage.accounts'
import { Route as GenerateUpscalerRouteImport } from './routes/generate.upscaler'
import { Route as GenerateTextToVideoRouteImport } from './routes/generate.text-to-video'
import { Route as GenerateStoryboardRouteImport } from './routes/generate.storyboard'
import { Route as GenerateNaratifRouteImport } from './routes/generate.naratif'
import { Route as GenerateMotionRouteImport } from './routes/generate.motion'
import { Route as GenerateLeonardoRouteImport } from './routes/generate.leonardo'
import { Route as GenerateImageToVideoRouteImport } from './routes/generate.image-to-video'
import { Route as GenerateFramiaRouteImport } from './routes/generate.framia'
import { Route as GenerateBulkFashionRouteImport } from './routes/generate.bulk-fashion'
import { Route as DevWeavyTestRouteImport } from './routes/dev.weavy-test'
import { Route as DevWeavyNodeInspectRouteImport } from './routes/dev.weavy-node-inspect'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy-image'
import { Route as AiInfluencerPublisherRouteImport } from './routes/ai-influencer.publisher'
import { Route as AiInfluencerPlannerRouteImport } from './routes/ai-influencer.planner'
import { Route as AiInfluencerLibraryRouteImport } from './routes/ai-influencer.library'
import { Route as AiInfluencerCharacterRouteImport } from './routes/ai-influencer.character'
import { Route as AiInfluencerBrainRouteImport } from './routes/ai-influencer.brain'
import { Route as AiInfluencerAnalyticsRouteImport } from './routes/ai-influencer.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTokenBankRouteImport } from './routes/admin.token-bank'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminActivityLogRouteImport } from './routes/admin.activity-log'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth.google-drive.return'
import { Route as ApiRouterVoiceRouteImport } from './routes/api/router/voice'
import { Route as ApiRouterSubtitleRouteImport } from './routes/api/router/subtitle'
import { Route as ApiRouterSttRouteImport } from './routes/api/router/stt'
import { Route as ApiRouterRenderCloudRouteImport } from './routes/api/router/render-cloud'
import { Route as ApiRouterRenderRouteImport } from './routes/api/router/render'
import { Route as ApiRouterPlanWeeklyRouteImport } from './routes/api/router/plan-weekly'
import { Route as ApiRouterImageRouteImport } from './routes/api/router/image'
import { Route as ApiRouterChatRouteImport } from './routes/api/router/chat'
import { Route as ApiRouterBrainAnalyzeRouteImport } from './routes/api/router/brain-analyze'
import { Route as ApiPublicValidateMediaRouteImport } from './routes/api/public/validate-media'
import { Route as ApiPublicUploadCatboxRouteImport } from './routes/api/public/upload-catbox'
import { Route as ApiPublicStoryboardBrainRouteImport } from './routes/api/public/storyboard-brain'
import { Route as ApiPublicScrapeProductRouteImport } from './routes/api/public/scrape-product'
import { Route as ApiPublicScrapeArticleRouteImport } from './routes/api/public/scrape-article'
import { Route as ApiPublicRoboneoMembershipRouteImport } from './routes/api/public/roboneo-membership'
import { Route as ApiPublicRoboneoRouteImport } from './routes/api/public/roboneo'
import { Route as ApiPublicProxyImageRouteImport } from './routes/api/public/proxy-image'
import { Route as ApiPublicNewsFeedRouteImport } from './routes/api/public/news-feed'
import { Route as ApiPublicNaratifBrainRouteImport } from './routes/api/public/naratif-brain'
import { Route as ApiPublicMagnificRouteImport } from './routes/api/public/magnific'
import { Route as ApiPublicLeonardoCognitoRouteImport } from './routes/api/public/leonardo-cognito'
import { Route as ApiPublicLeonardoRouteImport } from './routes/api/public/leonardo'
import { Route as ApiPublicFramiaRouteImport } from './routes/api/public/framia'
import { Route as ApiPublicFireflyRouteImport } from './routes/api/public/firefly'
import { Route as ApiPublicFfmpegCdnRouteImport } from './routes/api/public/ffmpeg-cdn'
import { Route as ApiPublicElevenlabsValidateRouteImport } from './routes/api/public/elevenlabs-validate'
import { Route as ApiPublicElevenlabsTtsRouteImport } from './routes/api/public/elevenlabs-tts'
import { Route as ApiPublicDubbingBrainRouteImport } from './routes/api/public/dubbing-brain'
import { Route as ApiPublicCreativeBrainRouteImport } from './routes/api/public/creative-brain'
import { Route as ApiPublicClipperBrainRouteImport } from './routes/api/public/clipper-brain'
import { Route as ApiPublicBacksoundSearchRouteImport } from './routes/api/public/backsound-search'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok/callback'
import { Route as ApiPublicMidtransNotificationRouteImport } from './routes/api/public/midtrans/notification'
import { Route as ApiPublicGoogleDriveCallbackRouteImport } from './routes/api/public/google-drive/callback'
import { Route as ApiPublicExtensionRefreshRouteImport } from './routes/api/public/extension/refresh'
import { Route as ApiPublicExtensionPushTokenRouteImport } from './routes/api/public/extension/push-token'
import { Route as ApiPublicExtensionLoginRouteImport } from './routes/api/public/extension/login'
import { Route as ApiPublicDokuNotificationRouteImport } from './routes/api/public/doku/notification'
import { Route as ApiPublicCloudUploadRouteImport } from './routes/api/public/cloud/upload'
import { Route as ApiPublicCloudFileIdRouteImport } from './routes/api/public/cloud/file.$id'

const ReffEditRoute = ReffEditRouteImport.update({
  id: '/reff-edit',
  path: '/reff-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MixingRoute = MixingRouteImport.update({
  id: '/mixing',
  path: '/mixing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerRoute = AiInfluencerRouteImport.update({
  id: '/ai-influencer',
  path: '/ai-influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerIndexRoute = AiInfluencerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHelpRoute = SystemHelpRouteImport.update({
  id: '/system/help',
  path: '/system/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCloudRoute = SystemCloudRouteImport.update({
  id: '/system/cloud',
  path: '/system/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAnalyticRoute = SystemAnalyticRouteImport.update({
  id: '/system/analytic',
  path: '/system/analytic',
  getParentRoute: () => rootRouteImport,
} as any)
const ReffEditVideoRoute = ReffEditVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ReffEditRoute,
} as any)
const ReffEditImageRoute = ReffEditImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ReffEditRoute,
} as any)
const ReffEditHistoryRoute = ReffEditHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReffEditRoute,
} as any)
const MixingDubbingRoute = MixingDubbingRouteImport.update({
  id: '/dubbing',
  path: '/dubbing',
  getParentRoute: () => MixingRoute,
} as any)
const MixingClipperRoute = MixingClipperRouteImport.update({
  id: '/clipper',
  path: '/clipper',
  getParentRoute: () => MixingRoute,
} as any)
const ManageTokensRoute = ManageTokensRouteImport.update({
  id: '/manage/tokens',
  path: '/manage/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoutingRoute = ManageRoutingRouteImport.update({
  id: '/manage/routing',
  path: '/manage/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAccountsRoute = ManageAccountsRouteImport.update({
  id: '/manage/accounts',
  path: '/manage/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateUpscalerRoute = GenerateUpscalerRouteImport.update({
  id: '/generate/upscaler',
  path: '/generate/upscaler',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateTextToVideoRoute = GenerateTextToVideoRouteImport.update({
  id: '/generate/text-to-video',
  path: '/generate/text-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateStoryboardRoute = GenerateStoryboardRouteImport.update({
  id: '/generate/storyboard',
  path: '/generate/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateNaratifRoute = GenerateNaratifRouteImport.update({
  id: '/generate/naratif',
  path: '/generate/naratif',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateMotionRoute = GenerateMotionRouteImport.update({
  id: '/generate/motion',
  path: '/generate/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateLeonardoRoute = GenerateLeonardoRouteImport.update({
  id: '/generate/leonardo',
  path: '/generate/leonardo',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateImageToVideoRoute = GenerateImageToVideoRouteImport.update({
  id: '/generate/image-to-video',
  path: '/generate/image-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateFramiaRoute = GenerateFramiaRouteImport.update({
  id: '/generate/framia',
  path: '/generate/framia',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateBulkFashionRoute = GenerateBulkFashionRouteImport.update({
  id: '/generate/bulk-fashion',
  path: '/generate/bulk-fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWeavyTestRoute = DevWeavyTestRouteImport.update({
  id: '/dev/weavy-test',
  path: '/dev/weavy-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWeavyNodeInspectRoute = DevWeavyNodeInspectRouteImport.update({
  id: '/dev/weavy-node-inspect',
  path: '/dev/weavy-node-inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfluencerPublisherRoute = AiInfluencerPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerPlannerRoute = AiInfluencerPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerLibraryRoute = AiInfluencerLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerCharacterRoute = AiInfluencerCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerBrainRoute = AiInfluencerBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AiInfluencerAnalyticsRoute = AiInfluencerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AiInfluencerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokenBankRoute = AdminTokenBankRouteImport.update({
  id: '/token-bank',
  path: '/token-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogRoute = AdminActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterVoiceRoute = ApiRouterVoiceRouteImport.update({
  id: '/api/router/voice',
  path: '/api/router/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterSubtitleRoute = ApiRouterSubtitleRouteImport.update({
  id: '/api/router/subtitle',
  path: '/api/router/subtitle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterSttRoute = ApiRouterSttRouteImport.update({
  id: '/api/router/stt',
  path: '/api/router/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterRenderCloudRoute = ApiRouterRenderCloudRouteImport.update({
  id: '/api/router/render-cloud',
  path: '/api/router/render-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterRenderRoute = ApiRouterRenderRouteImport.update({
  id: '/api/router/render',
  path: '/api/router/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterPlanWeeklyRoute = ApiRouterPlanWeeklyRouteImport.update({
  id: '/api/router/plan-weekly',
  path: '/api/router/plan-weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterImageRoute = ApiRouterImageRouteImport.update({
  id: '/api/router/image',
  path: '/api/router/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterChatRoute = ApiRouterChatRouteImport.update({
  id: '/api/router/chat',
  path: '/api/router/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouterBrainAnalyzeRoute = ApiRouterBrainAnalyzeRouteImport.update({
  id: '/api/router/brain-analyze',
  path: '/api/router/brain-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicValidateMediaRoute = ApiPublicValidateMediaRouteImport.update({
  id: '/api/public/validate-media',
  path: '/api/public/validate-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadCatboxRoute = ApiPublicUploadCatboxRouteImport.update({
  id: '/api/public/upload-catbox',
  path: '/api/public/upload-catbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoryboardBrainRoute =
  ApiPublicStoryboardBrainRouteImport.update({
    id: '/api/public/storyboard-brain',
    path: '/api/public/storyboard-brain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScrapeProductRoute = ApiPublicScrapeProductRouteImport.update({
  id: '/api/public/scrape-product',
  path: '/api/public/scrape-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapeArticleRoute = ApiPublicScrapeArticleRouteImport.update({
  id: '/api/public/scrape-article',
  path: '/api/public/scrape-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoboneoMembershipRoute =
  ApiPublicRoboneoMembershipRouteImport.update({
    id: '/api/public/roboneo-membership',
    path: '/api/public/roboneo-membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRoboneoRoute = ApiPublicRoboneoRouteImport.update({
  id: '/api/public/roboneo',
  path: '/api/public/roboneo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyImageRoute = ApiPublicProxyImageRouteImport.update({
  id: '/api/public/proxy-image',
  path: '/api/public/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsFeedRoute = ApiPublicNewsFeedRouteImport.update({
  id: '/api/public/news-feed',
  path: '/api/public/news-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNaratifBrainRoute = ApiPublicNaratifBrainRouteImport.update({
  id: '/api/public/naratif-brain',
  path: '/api/public/naratif-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMagnificRoute = ApiPublicMagnificRouteImport.update({
  id: '/api/public/magnific',
  path: '/api/public/magnific',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeonardoCognitoRoute =
  ApiPublicLeonardoCognitoRouteImport.update({
    id: '/api/public/leonardo-cognito',
    path: '/api/public/leonardo-cognito',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeonardoRoute = ApiPublicLeonardoRouteImport.update({
  id: '/api/public/leonardo',
  path: '/api/public/leonardo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFramiaRoute = ApiPublicFramiaRouteImport.update({
  id: '/api/public/framia',
  path: '/api/public/framia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFireflyRoute = ApiPublicFireflyRouteImport.update({
  id: '/api/public/firefly',
  path: '/api/public/firefly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFfmpegCdnRoute = ApiPublicFfmpegCdnRouteImport.update({
  id: '/api/public/ffmpeg-cdn',
  path: '/api/public/ffmpeg-cdn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsValidateRoute =
  ApiPublicElevenlabsValidateRouteImport.update({
    id: '/api/public/elevenlabs-validate',
    path: '/api/public/elevenlabs-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsTtsRoute = ApiPublicElevenlabsTtsRouteImport.update({
  id: '/api/public/elevenlabs-tts',
  path: '/api/public/elevenlabs-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDubbingBrainRoute = ApiPublicDubbingBrainRouteImport.update({
  id: '/api/public/dubbing-brain',
  path: '/api/public/dubbing-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreativeBrainRoute = ApiPublicCreativeBrainRouteImport.update({
  id: '/api/public/creative-brain',
  path: '/api/public/creative-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipperBrainRoute = ApiPublicClipperBrainRouteImport.update({
  id: '/api/public/clipper-brain',
  path: '/api/public/clipper-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBacksoundSearchRoute =
  ApiPublicBacksoundSearchRouteImport.update({
    id: '/api/public/backsound-search',
    path: '/api/public/backsound-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMidtransNotificationRoute =
  ApiPublicMidtransNotificationRouteImport.update({
    id: '/api/public/midtrans/notification',
    path: '/api/public/midtrans/notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleDriveCallbackRoute =
  ApiPublicGoogleDriveCallbackRouteImport.update({
    id: '/api/public/google-drive/callback',
    path: '/api/public/google-drive/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionRefreshRoute =
  ApiPublicExtensionRefreshRouteImport.update({
    id: '/api/public/extension/refresh',
    path: '/api/public/extension/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionPushTokenRoute =
  ApiPublicExtensionPushTokenRouteImport.update({
    id: '/api/public/extension/push-token',
    path: '/api/public/extension/push-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionLoginRoute = ApiPublicExtensionLoginRouteImport.update({
  id: '/api/public/extension/login',
  path: '/api/public/extension/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDokuNotificationRoute =
  ApiPublicDokuNotificationRouteImport.update({
    id: '/api/public/doku/notification',
    path: '/api/public/doku/notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudUploadRoute = ApiPublicCloudUploadRouteImport.update({
  id: '/api/public/cloud/upload',
  path: '/api/public/cloud/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudFileIdRoute = ApiPublicCloudFileIdRouteImport.update({
  id: '/api/public/cloud/file/$id',
  path: '/api/public/cloud/file/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-influencer': typeof AiInfluencerRouteWithChildren
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reff-edit': typeof ReffEditRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-node-inspect': typeof DevWeavyNodeInspectRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/framia': typeof GenerateFramiaRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/leonardo': typeof GenerateLeonardoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/generate/text-to-video': typeof GenerateTextToVideoRoute
  '/generate/upscaler': typeof GenerateUpscalerRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/reff-edit/history': typeof ReffEditHistoryRoute
  '/reff-edit/image': typeof ReffEditImageRoute
  '/reff-edit/video': typeof ReffEditVideoRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/cloud': typeof SystemCloudRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-influencer/': typeof AiInfluencerIndexRoute
  '/api/public/backsound-search': typeof ApiPublicBacksoundSearchRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/firefly': typeof ApiPublicFireflyRoute
  '/api/public/framia': typeof ApiPublicFramiaRoute
  '/api/public/leonardo': typeof ApiPublicLeonardoRoute
  '/api/public/leonardo-cognito': typeof ApiPublicLeonardoCognitoRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/news-feed': typeof ApiPublicNewsFeedRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/roboneo': typeof ApiPublicRoboneoRoute
  '/api/public/roboneo-membership': typeof ApiPublicRoboneoMembershipRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/public/validate-media': typeof ApiPublicValidateMediaRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/cloud/upload': typeof ApiPublicCloudUploadRoute
  '/api/public/doku/notification': typeof ApiPublicDokuNotificationRoute
  '/api/public/extension/login': typeof ApiPublicExtensionLoginRoute
  '/api/public/extension/push-token': typeof ApiPublicExtensionPushTokenRoute
  '/api/public/extension/refresh': typeof ApiPublicExtensionRefreshRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/cloud/file/$id': typeof ApiPublicCloudFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reff-edit': typeof ReffEditRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-node-inspect': typeof DevWeavyNodeInspectRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/framia': typeof GenerateFramiaRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/leonardo': typeof GenerateLeonardoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/generate/text-to-video': typeof GenerateTextToVideoRoute
  '/generate/upscaler': typeof GenerateUpscalerRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/reff-edit/history': typeof ReffEditHistoryRoute
  '/reff-edit/image': typeof ReffEditImageRoute
  '/reff-edit/video': typeof ReffEditVideoRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/cloud': typeof SystemCloudRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/ai-influencer': typeof AiInfluencerIndexRoute
  '/api/public/backsound-search': typeof ApiPublicBacksoundSearchRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/firefly': typeof ApiPublicFireflyRoute
  '/api/public/framia': typeof ApiPublicFramiaRoute
  '/api/public/leonardo': typeof ApiPublicLeonardoRoute
  '/api/public/leonardo-cognito': typeof ApiPublicLeonardoCognitoRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/news-feed': typeof ApiPublicNewsFeedRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/roboneo': typeof ApiPublicRoboneoRoute
  '/api/public/roboneo-membership': typeof ApiPublicRoboneoMembershipRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/public/validate-media': typeof ApiPublicValidateMediaRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/cloud/upload': typeof ApiPublicCloudUploadRoute
  '/api/public/doku/notification': typeof ApiPublicDokuNotificationRoute
  '/api/public/extension/login': typeof ApiPublicExtensionLoginRoute
  '/api/public/extension/push-token': typeof ApiPublicExtensionPushTokenRoute
  '/api/public/extension/refresh': typeof ApiPublicExtensionRefreshRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/cloud/file/$id': typeof ApiPublicCloudFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-influencer': typeof AiInfluencerRouteWithChildren
  '/mixing': typeof MixingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reff-edit': typeof ReffEditRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/token-bank': typeof AdminTokenBankRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-influencer/analytics': typeof AiInfluencerAnalyticsRoute
  '/ai-influencer/brain': typeof AiInfluencerBrainRoute
  '/ai-influencer/character': typeof AiInfluencerCharacterRoute
  '/ai-influencer/library': typeof AiInfluencerLibraryRoute
  '/ai-influencer/planner': typeof AiInfluencerPlannerRoute
  '/ai-influencer/publisher': typeof AiInfluencerPublisherRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/weavy-node-inspect': typeof DevWeavyNodeInspectRoute
  '/dev/weavy-test': typeof DevWeavyTestRoute
  '/generate/bulk-fashion': typeof GenerateBulkFashionRoute
  '/generate/framia': typeof GenerateFramiaRoute
  '/generate/image-to-video': typeof GenerateImageToVideoRoute
  '/generate/leonardo': typeof GenerateLeonardoRoute
  '/generate/motion': typeof GenerateMotionRoute
  '/generate/naratif': typeof GenerateNaratifRoute
  '/generate/storyboard': typeof GenerateStoryboardRoute
  '/generate/text-to-video': typeof GenerateTextToVideoRoute
  '/generate/upscaler': typeof GenerateUpscalerRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/routing': typeof ManageRoutingRoute
  '/manage/tokens': typeof ManageTokensRoute
  '/mixing/clipper': typeof MixingClipperRoute
  '/mixing/dubbing': typeof MixingDubbingRoute
  '/reff-edit/history': typeof ReffEditHistoryRoute
  '/reff-edit/image': typeof ReffEditImageRoute
  '/reff-edit/video': typeof ReffEditVideoRoute
  '/system/analytic': typeof SystemAnalyticRoute
  '/system/cloud': typeof SystemCloudRoute
  '/system/help': typeof SystemHelpRoute
  '/system/settings': typeof SystemSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-influencer/': typeof AiInfluencerIndexRoute
  '/api/public/backsound-search': typeof ApiPublicBacksoundSearchRoute
  '/api/public/clipper-brain': typeof ApiPublicClipperBrainRoute
  '/api/public/creative-brain': typeof ApiPublicCreativeBrainRoute
  '/api/public/dubbing-brain': typeof ApiPublicDubbingBrainRoute
  '/api/public/elevenlabs-tts': typeof ApiPublicElevenlabsTtsRoute
  '/api/public/elevenlabs-validate': typeof ApiPublicElevenlabsValidateRoute
  '/api/public/ffmpeg-cdn': typeof ApiPublicFfmpegCdnRoute
  '/api/public/firefly': typeof ApiPublicFireflyRoute
  '/api/public/framia': typeof ApiPublicFramiaRoute
  '/api/public/leonardo': typeof ApiPublicLeonardoRoute
  '/api/public/leonardo-cognito': typeof ApiPublicLeonardoCognitoRoute
  '/api/public/magnific': typeof ApiPublicMagnificRoute
  '/api/public/naratif-brain': typeof ApiPublicNaratifBrainRoute
  '/api/public/news-feed': typeof ApiPublicNewsFeedRoute
  '/api/public/proxy-image': typeof ApiPublicProxyImageRoute
  '/api/public/roboneo': typeof ApiPublicRoboneoRoute
  '/api/public/roboneo-membership': typeof ApiPublicRoboneoMembershipRoute
  '/api/public/scrape-article': typeof ApiPublicScrapeArticleRoute
  '/api/public/scrape-product': typeof ApiPublicScrapeProductRoute
  '/api/public/storyboard-brain': typeof ApiPublicStoryboardBrainRoute
  '/api/public/upload-catbox': typeof ApiPublicUploadCatboxRoute
  '/api/public/validate-media': typeof ApiPublicValidateMediaRoute
  '/api/router/brain-analyze': typeof ApiRouterBrainAnalyzeRoute
  '/api/router/chat': typeof ApiRouterChatRoute
  '/api/router/image': typeof ApiRouterImageRoute
  '/api/router/plan-weekly': typeof ApiRouterPlanWeeklyRoute
  '/api/router/render': typeof ApiRouterRenderRoute
  '/api/router/render-cloud': typeof ApiRouterRenderCloudRoute
  '/api/router/stt': typeof ApiRouterSttRoute
  '/api/router/subtitle': typeof ApiRouterSubtitleRoute
  '/api/router/voice': typeof ApiRouterVoiceRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/cloud/upload': typeof ApiPublicCloudUploadRoute
  '/api/public/doku/notification': typeof ApiPublicDokuNotificationRoute
  '/api/public/extension/login': typeof ApiPublicExtensionLoginRoute
  '/api/public/extension/push-token': typeof ApiPublicExtensionPushTokenRoute
  '/api/public/extension/refresh': typeof ApiPublicExtensionRefreshRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/api/public/midtrans/notification': typeof ApiPublicMidtransNotificationRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/cloud/file/$id': typeof ApiPublicCloudFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-influencer'
    | '/mixing'
    | '/profile'
    | '/reff-edit'
    | '/admin/access'
    | '/admin/activity-log'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/admin/users'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-node-inspect'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/framia'
    | '/generate/image-to-video'
    | '/generate/leonardo'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/generate/text-to-video'
    | '/generate/upscaler'
    | '/manage/accounts'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/reff-edit/history'
    | '/reff-edit/image'
    | '/reff-edit/video'
    | '/system/analytic'
    | '/system/cloud'
    | '/system/help'
    | '/system/settings'
    | '/admin/'
    | '/ai-influencer/'
    | '/api/public/backsound-search'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/firefly'
    | '/api/public/framia'
    | '/api/public/leonardo'
    | '/api/public/leonardo-cognito'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/news-feed'
    | '/api/public/proxy-image'
    | '/api/public/roboneo'
    | '/api/public/roboneo-membership'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/public/validate-media'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/voice'
    | '/oauth/google-drive/return'
    | '/api/public/cloud/upload'
    | '/api/public/doku/notification'
    | '/api/public/extension/login'
    | '/api/public/extension/push-token'
    | '/api/public/extension/refresh'
    | '/api/public/google-drive/callback'
    | '/api/public/midtrans/notification'
    | '/api/public/tiktok/callback'
    | '/api/public/cloud/file/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mixing'
    | '/profile'
    | '/reff-edit'
    | '/admin/access'
    | '/admin/activity-log'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/admin/users'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-node-inspect'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/framia'
    | '/generate/image-to-video'
    | '/generate/leonardo'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/generate/text-to-video'
    | '/generate/upscaler'
    | '/manage/accounts'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/reff-edit/history'
    | '/reff-edit/image'
    | '/reff-edit/video'
    | '/system/analytic'
    | '/system/cloud'
    | '/system/help'
    | '/system/settings'
    | '/admin'
    | '/ai-influencer'
    | '/api/public/backsound-search'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/firefly'
    | '/api/public/framia'
    | '/api/public/leonardo'
    | '/api/public/leonardo-cognito'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/news-feed'
    | '/api/public/proxy-image'
    | '/api/public/roboneo'
    | '/api/public/roboneo-membership'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/public/validate-media'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/voice'
    | '/oauth/google-drive/return'
    | '/api/public/cloud/upload'
    | '/api/public/doku/notification'
    | '/api/public/extension/login'
    | '/api/public/extension/push-token'
    | '/api/public/extension/refresh'
    | '/api/public/google-drive/callback'
    | '/api/public/midtrans/notification'
    | '/api/public/tiktok/callback'
    | '/api/public/cloud/file/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-influencer'
    | '/mixing'
    | '/profile'
    | '/reff-edit'
    | '/admin/access'
    | '/admin/activity-log'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/token-bank'
    | '/admin/transactions'
    | '/admin/users'
    | '/ai-influencer/analytics'
    | '/ai-influencer/brain'
    | '/ai-influencer/character'
    | '/ai-influencer/library'
    | '/ai-influencer/planner'
    | '/ai-influencer/publisher'
    | '/api/proxy-image'
    | '/auth/callback'
    | '/dev/weavy-node-inspect'
    | '/dev/weavy-test'
    | '/generate/bulk-fashion'
    | '/generate/framia'
    | '/generate/image-to-video'
    | '/generate/leonardo'
    | '/generate/motion'
    | '/generate/naratif'
    | '/generate/storyboard'
    | '/generate/text-to-video'
    | '/generate/upscaler'
    | '/manage/accounts'
    | '/manage/routing'
    | '/manage/tokens'
    | '/mixing/clipper'
    | '/mixing/dubbing'
    | '/reff-edit/history'
    | '/reff-edit/image'
    | '/reff-edit/video'
    | '/system/analytic'
    | '/system/cloud'
    | '/system/help'
    | '/system/settings'
    | '/admin/'
    | '/ai-influencer/'
    | '/api/public/backsound-search'
    | '/api/public/clipper-brain'
    | '/api/public/creative-brain'
    | '/api/public/dubbing-brain'
    | '/api/public/elevenlabs-tts'
    | '/api/public/elevenlabs-validate'
    | '/api/public/ffmpeg-cdn'
    | '/api/public/firefly'
    | '/api/public/framia'
    | '/api/public/leonardo'
    | '/api/public/leonardo-cognito'
    | '/api/public/magnific'
    | '/api/public/naratif-brain'
    | '/api/public/news-feed'
    | '/api/public/proxy-image'
    | '/api/public/roboneo'
    | '/api/public/roboneo-membership'
    | '/api/public/scrape-article'
    | '/api/public/scrape-product'
    | '/api/public/storyboard-brain'
    | '/api/public/upload-catbox'
    | '/api/public/validate-media'
    | '/api/router/brain-analyze'
    | '/api/router/chat'
    | '/api/router/image'
    | '/api/router/plan-weekly'
    | '/api/router/render'
    | '/api/router/render-cloud'
    | '/api/router/stt'
    | '/api/router/subtitle'
    | '/api/router/voice'
    | '/oauth/google-drive/return'
    | '/api/public/cloud/upload'
    | '/api/public/doku/notification'
    | '/api/public/extension/login'
    | '/api/public/extension/push-token'
    | '/api/public/extension/refresh'
    | '/api/public/google-drive/callback'
    | '/api/public/midtrans/notification'
    | '/api/public/tiktok/callback'
    | '/api/public/cloud/file/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiInfluencerRoute: typeof AiInfluencerRouteWithChildren
  MixingRoute: typeof MixingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReffEditRoute: typeof ReffEditRouteWithChildren
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevWeavyNodeInspectRoute: typeof DevWeavyNodeInspectRoute
  DevWeavyTestRoute: typeof DevWeavyTestRoute
  GenerateBulkFashionRoute: typeof GenerateBulkFashionRoute
  GenerateFramiaRoute: typeof GenerateFramiaRoute
  GenerateImageToVideoRoute: typeof GenerateImageToVideoRoute
  GenerateLeonardoRoute: typeof GenerateLeonardoRoute
  GenerateMotionRoute: typeof GenerateMotionRoute
  GenerateNaratifRoute: typeof GenerateNaratifRoute
  GenerateStoryboardRoute: typeof GenerateStoryboardRoute
  GenerateTextToVideoRoute: typeof GenerateTextToVideoRoute
  GenerateUpscalerRoute: typeof GenerateUpscalerRoute
  ManageAccountsRoute: typeof ManageAccountsRoute
  ManageRoutingRoute: typeof ManageRoutingRoute
  ManageTokensRoute: typeof ManageTokensRoute
  SystemAnalyticRoute: typeof SystemAnalyticRoute
  SystemCloudRoute: typeof SystemCloudRoute
  SystemHelpRoute: typeof SystemHelpRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  ApiPublicBacksoundSearchRoute: typeof ApiPublicBacksoundSearchRoute
  ApiPublicClipperBrainRoute: typeof ApiPublicClipperBrainRoute
  ApiPublicCreativeBrainRoute: typeof ApiPublicCreativeBrainRoute
  ApiPublicDubbingBrainRoute: typeof ApiPublicDubbingBrainRoute
  ApiPublicElevenlabsTtsRoute: typeof ApiPublicElevenlabsTtsRoute
  ApiPublicElevenlabsValidateRoute: typeof ApiPublicElevenlabsValidateRoute
  ApiPublicFfmpegCdnRoute: typeof ApiPublicFfmpegCdnRoute
  ApiPublicFireflyRoute: typeof ApiPublicFireflyRoute
  ApiPublicFramiaRoute: typeof ApiPublicFramiaRoute
  ApiPublicLeonardoRoute: typeof ApiPublicLeonardoRoute
  ApiPublicLeonardoCognitoRoute: typeof ApiPublicLeonardoCognitoRoute
  ApiPublicMagnificRoute: typeof ApiPublicMagnificRoute
  ApiPublicNaratifBrainRoute: typeof ApiPublicNaratifBrainRoute
  ApiPublicNewsFeedRoute: typeof ApiPublicNewsFeedRoute
  ApiPublicProxyImageRoute: typeof ApiPublicProxyImageRoute
  ApiPublicRoboneoRoute: typeof ApiPublicRoboneoRoute
  ApiPublicRoboneoMembershipRoute: typeof ApiPublicRoboneoMembershipRoute
  ApiPublicScrapeArticleRoute: typeof ApiPublicScrapeArticleRoute
  ApiPublicScrapeProductRoute: typeof ApiPublicScrapeProductRoute
  ApiPublicStoryboardBrainRoute: typeof ApiPublicStoryboardBrainRoute
  ApiPublicUploadCatboxRoute: typeof ApiPublicUploadCatboxRoute
  ApiPublicValidateMediaRoute: typeof ApiPublicValidateMediaRoute
  ApiRouterBrainAnalyzeRoute: typeof ApiRouterBrainAnalyzeRoute
  ApiRouterChatRoute: typeof ApiRouterChatRoute
  ApiRouterImageRoute: typeof ApiRouterImageRoute
  ApiRouterPlanWeeklyRoute: typeof ApiRouterPlanWeeklyRoute
  ApiRouterRenderRoute: typeof ApiRouterRenderRoute
  ApiRouterRenderCloudRoute: typeof ApiRouterRenderCloudRoute
  ApiRouterSttRoute: typeof ApiRouterSttRoute
  ApiRouterSubtitleRoute: typeof ApiRouterSubtitleRoute
  ApiRouterVoiceRoute: typeof ApiRouterVoiceRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
  ApiPublicCloudUploadRoute: typeof ApiPublicCloudUploadRoute
  ApiPublicDokuNotificationRoute: typeof ApiPublicDokuNotificationRoute
  ApiPublicExtensionLoginRoute: typeof ApiPublicExtensionLoginRoute
  ApiPublicExtensionPushTokenRoute: typeof ApiPublicExtensionPushTokenRoute
  ApiPublicExtensionRefreshRoute: typeof ApiPublicExtensionRefreshRoute
  ApiPublicGoogleDriveCallbackRoute: typeof ApiPublicGoogleDriveCallbackRoute
  ApiPublicMidtransNotificationRoute: typeof ApiPublicMidtransNotificationRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
  ApiPublicCloudFileIdRoute: typeof ApiPublicCloudFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reff-edit': {
      id: '/reff-edit'
      path: '/reff-edit'
      fullPath: '/reff-edit'
      preLoaderRoute: typeof ReffEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixing': {
      id: '/mixing'
      path: '/mixing'
      fullPath: '/mixing'
      preLoaderRoute: typeof MixingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer': {
      id: '/ai-influencer'
      path: '/ai-influencer'
      fullPath: '/ai-influencer'
      preLoaderRoute: typeof AiInfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer/': {
      id: '/ai-influencer/'
      path: '/'
      fullPath: '/ai-influencer/'
      preLoaderRoute: typeof AiInfluencerIndexRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/help': {
      id: '/system/help'
      path: '/system/help'
      fullPath: '/system/help'
      preLoaderRoute: typeof SystemHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/cloud': {
      id: '/system/cloud'
      path: '/system/cloud'
      fullPath: '/system/cloud'
      preLoaderRoute: typeof SystemCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/analytic': {
      id: '/system/analytic'
      path: '/system/analytic'
      fullPath: '/system/analytic'
      preLoaderRoute: typeof SystemAnalyticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reff-edit/video': {
      id: '/reff-edit/video'
      path: '/video'
      fullPath: '/reff-edit/video'
      preLoaderRoute: typeof ReffEditVideoRouteImport
      parentRoute: typeof ReffEditRoute
    }
    '/reff-edit/image': {
      id: '/reff-edit/image'
      path: '/image'
      fullPath: '/reff-edit/image'
      preLoaderRoute: typeof ReffEditImageRouteImport
      parentRoute: typeof ReffEditRoute
    }
    '/reff-edit/history': {
      id: '/reff-edit/history'
      path: '/history'
      fullPath: '/reff-edit/history'
      preLoaderRoute: typeof ReffEditHistoryRouteImport
      parentRoute: typeof ReffEditRoute
    }
    '/mixing/dubbing': {
      id: '/mixing/dubbing'
      path: '/dubbing'
      fullPath: '/mixing/dubbing'
      preLoaderRoute: typeof MixingDubbingRouteImport
      parentRoute: typeof MixingRoute
    }
    '/mixing/clipper': {
      id: '/mixing/clipper'
      path: '/clipper'
      fullPath: '/mixing/clipper'
      preLoaderRoute: typeof MixingClipperRouteImport
      parentRoute: typeof MixingRoute
    }
    '/manage/tokens': {
      id: '/manage/tokens'
      path: '/manage/tokens'
      fullPath: '/manage/tokens'
      preLoaderRoute: typeof ManageTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/routing': {
      id: '/manage/routing'
      path: '/manage/routing'
      fullPath: '/manage/routing'
      preLoaderRoute: typeof ManageRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/accounts': {
      id: '/manage/accounts'
      path: '/manage/accounts'
      fullPath: '/manage/accounts'
      preLoaderRoute: typeof ManageAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/upscaler': {
      id: '/generate/upscaler'
      path: '/generate/upscaler'
      fullPath: '/generate/upscaler'
      preLoaderRoute: typeof GenerateUpscalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/text-to-video': {
      id: '/generate/text-to-video'
      path: '/generate/text-to-video'
      fullPath: '/generate/text-to-video'
      preLoaderRoute: typeof GenerateTextToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/storyboard': {
      id: '/generate/storyboard'
      path: '/generate/storyboard'
      fullPath: '/generate/storyboard'
      preLoaderRoute: typeof GenerateStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/naratif': {
      id: '/generate/naratif'
      path: '/generate/naratif'
      fullPath: '/generate/naratif'
      preLoaderRoute: typeof GenerateNaratifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/motion': {
      id: '/generate/motion'
      path: '/generate/motion'
      fullPath: '/generate/motion'
      preLoaderRoute: typeof GenerateMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/leonardo': {
      id: '/generate/leonardo'
      path: '/generate/leonardo'
      fullPath: '/generate/leonardo'
      preLoaderRoute: typeof GenerateLeonardoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/image-to-video': {
      id: '/generate/image-to-video'
      path: '/generate/image-to-video'
      fullPath: '/generate/image-to-video'
      preLoaderRoute: typeof GenerateImageToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/framia': {
      id: '/generate/framia'
      path: '/generate/framia'
      fullPath: '/generate/framia'
      preLoaderRoute: typeof GenerateFramiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/bulk-fashion': {
      id: '/generate/bulk-fashion'
      path: '/generate/bulk-fashion'
      fullPath: '/generate/bulk-fashion'
      preLoaderRoute: typeof GenerateBulkFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/weavy-test': {
      id: '/dev/weavy-test'
      path: '/dev/weavy-test'
      fullPath: '/dev/weavy-test'
      preLoaderRoute: typeof DevWeavyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/weavy-node-inspect': {
      id: '/dev/weavy-node-inspect'
      path: '/dev/weavy-node-inspect'
      fullPath: '/dev/weavy-node-inspect'
      preLoaderRoute: typeof DevWeavyNodeInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-influencer/publisher': {
      id: '/ai-influencer/publisher'
      path: '/publisher'
      fullPath: '/ai-influencer/publisher'
      preLoaderRoute: typeof AiInfluencerPublisherRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/planner': {
      id: '/ai-influencer/planner'
      path: '/planner'
      fullPath: '/ai-influencer/planner'
      preLoaderRoute: typeof AiInfluencerPlannerRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/library': {
      id: '/ai-influencer/library'
      path: '/library'
      fullPath: '/ai-influencer/library'
      preLoaderRoute: typeof AiInfluencerLibraryRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/character': {
      id: '/ai-influencer/character'
      path: '/character'
      fullPath: '/ai-influencer/character'
      preLoaderRoute: typeof AiInfluencerCharacterRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/brain': {
      id: '/ai-influencer/brain'
      path: '/brain'
      fullPath: '/ai-influencer/brain'
      preLoaderRoute: typeof AiInfluencerBrainRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/ai-influencer/analytics': {
      id: '/ai-influencer/analytics'
      path: '/analytics'
      fullPath: '/ai-influencer/analytics'
      preLoaderRoute: typeof AiInfluencerAnalyticsRouteImport
      parentRoute: typeof AiInfluencerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/token-bank': {
      id: '/admin/token-bank'
      path: '/token-bank'
      fullPath: '/admin/token-bank'
      preLoaderRoute: typeof AdminTokenBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-log': {
      id: '/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AdminActivityLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/voice': {
      id: '/api/router/voice'
      path: '/api/router/voice'
      fullPath: '/api/router/voice'
      preLoaderRoute: typeof ApiRouterVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/subtitle': {
      id: '/api/router/subtitle'
      path: '/api/router/subtitle'
      fullPath: '/api/router/subtitle'
      preLoaderRoute: typeof ApiRouterSubtitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/stt': {
      id: '/api/router/stt'
      path: '/api/router/stt'
      fullPath: '/api/router/stt'
      preLoaderRoute: typeof ApiRouterSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/render-cloud': {
      id: '/api/router/render-cloud'
      path: '/api/router/render-cloud'
      fullPath: '/api/router/render-cloud'
      preLoaderRoute: typeof ApiRouterRenderCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/render': {
      id: '/api/router/render'
      path: '/api/router/render'
      fullPath: '/api/router/render'
      preLoaderRoute: typeof ApiRouterRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/plan-weekly': {
      id: '/api/router/plan-weekly'
      path: '/api/router/plan-weekly'
      fullPath: '/api/router/plan-weekly'
      preLoaderRoute: typeof ApiRouterPlanWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/image': {
      id: '/api/router/image'
      path: '/api/router/image'
      fullPath: '/api/router/image'
      preLoaderRoute: typeof ApiRouterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/chat': {
      id: '/api/router/chat'
      path: '/api/router/chat'
      fullPath: '/api/router/chat'
      preLoaderRoute: typeof ApiRouterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/router/brain-analyze': {
      id: '/api/router/brain-analyze'
      path: '/api/router/brain-analyze'
      fullPath: '/api/router/brain-analyze'
      preLoaderRoute: typeof ApiRouterBrainAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/validate-media': {
      id: '/api/public/validate-media'
      path: '/api/public/validate-media'
      fullPath: '/api/public/validate-media'
      preLoaderRoute: typeof ApiPublicValidateMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-catbox': {
      id: '/api/public/upload-catbox'
      path: '/api/public/upload-catbox'
      fullPath: '/api/public/upload-catbox'
      preLoaderRoute: typeof ApiPublicUploadCatboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/storyboard-brain': {
      id: '/api/public/storyboard-brain'
      path: '/api/public/storyboard-brain'
      fullPath: '/api/public/storyboard-brain'
      preLoaderRoute: typeof ApiPublicStoryboardBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape-product': {
      id: '/api/public/scrape-product'
      path: '/api/public/scrape-product'
      fullPath: '/api/public/scrape-product'
      preLoaderRoute: typeof ApiPublicScrapeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape-article': {
      id: '/api/public/scrape-article'
      path: '/api/public/scrape-article'
      fullPath: '/api/public/scrape-article'
      preLoaderRoute: typeof ApiPublicScrapeArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roboneo-membership': {
      id: '/api/public/roboneo-membership'
      path: '/api/public/roboneo-membership'
      fullPath: '/api/public/roboneo-membership'
      preLoaderRoute: typeof ApiPublicRoboneoMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roboneo': {
      id: '/api/public/roboneo'
      path: '/api/public/roboneo'
      fullPath: '/api/public/roboneo'
      preLoaderRoute: typeof ApiPublicRoboneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy-image': {
      id: '/api/public/proxy-image'
      path: '/api/public/proxy-image'
      fullPath: '/api/public/proxy-image'
      preLoaderRoute: typeof ApiPublicProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news-feed': {
      id: '/api/public/news-feed'
      path: '/api/public/news-feed'
      fullPath: '/api/public/news-feed'
      preLoaderRoute: typeof ApiPublicNewsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/naratif-brain': {
      id: '/api/public/naratif-brain'
      path: '/api/public/naratif-brain'
      fullPath: '/api/public/naratif-brain'
      preLoaderRoute: typeof ApiPublicNaratifBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/magnific': {
      id: '/api/public/magnific'
      path: '/api/public/magnific'
      fullPath: '/api/public/magnific'
      preLoaderRoute: typeof ApiPublicMagnificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leonardo-cognito': {
      id: '/api/public/leonardo-cognito'
      path: '/api/public/leonardo-cognito'
      fullPath: '/api/public/leonardo-cognito'
      preLoaderRoute: typeof ApiPublicLeonardoCognitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leonardo': {
      id: '/api/public/leonardo'
      path: '/api/public/leonardo'
      fullPath: '/api/public/leonardo'
      preLoaderRoute: typeof ApiPublicLeonardoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/framia': {
      id: '/api/public/framia'
      path: '/api/public/framia'
      fullPath: '/api/public/framia'
      preLoaderRoute: typeof ApiPublicFramiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firefly': {
      id: '/api/public/firefly'
      path: '/api/public/firefly'
      fullPath: '/api/public/firefly'
      preLoaderRoute: typeof ApiPublicFireflyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ffmpeg-cdn': {
      id: '/api/public/ffmpeg-cdn'
      path: '/api/public/ffmpeg-cdn'
      fullPath: '/api/public/ffmpeg-cdn'
      preLoaderRoute: typeof ApiPublicFfmpegCdnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-validate': {
      id: '/api/public/elevenlabs-validate'
      path: '/api/public/elevenlabs-validate'
      fullPath: '/api/public/elevenlabs-validate'
      preLoaderRoute: typeof ApiPublicElevenlabsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-tts': {
      id: '/api/public/elevenlabs-tts'
      path: '/api/public/elevenlabs-tts'
      fullPath: '/api/public/elevenlabs-tts'
      preLoaderRoute: typeof ApiPublicElevenlabsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dubbing-brain': {
      id: '/api/public/dubbing-brain'
      path: '/api/public/dubbing-brain'
      fullPath: '/api/public/dubbing-brain'
      preLoaderRoute: typeof ApiPublicDubbingBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/creative-brain': {
      id: '/api/public/creative-brain'
      path: '/api/public/creative-brain'
      fullPath: '/api/public/creative-brain'
      preLoaderRoute: typeof ApiPublicCreativeBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clipper-brain': {
      id: '/api/public/clipper-brain'
      path: '/api/public/clipper-brain'
      fullPath: '/api/public/clipper-brain'
      preLoaderRoute: typeof ApiPublicClipperBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backsound-search': {
      id: '/api/public/backsound-search'
      path: '/api/public/backsound-search'
      fullPath: '/api/public/backsound-search'
      preLoaderRoute: typeof ApiPublicBacksoundSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/midtrans/notification': {
      id: '/api/public/midtrans/notification'
      path: '/api/public/midtrans/notification'
      fullPath: '/api/public/midtrans/notification'
      preLoaderRoute: typeof ApiPublicMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-drive/callback': {
      id: '/api/public/google-drive/callback'
      path: '/api/public/google-drive/callback'
      fullPath: '/api/public/google-drive/callback'
      preLoaderRoute: typeof ApiPublicGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/refresh': {
      id: '/api/public/extension/refresh'
      path: '/api/public/extension/refresh'
      fullPath: '/api/public/extension/refresh'
      preLoaderRoute: typeof ApiPublicExtensionRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/push-token': {
      id: '/api/public/extension/push-token'
      path: '/api/public/extension/push-token'
      fullPath: '/api/public/extension/push-token'
      preLoaderRoute: typeof ApiPublicExtensionPushTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/login': {
      id: '/api/public/extension/login'
      path: '/api/public/extension/login'
      fullPath: '/api/public/extension/login'
      preLoaderRoute: typeof ApiPublicExtensionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/doku/notification': {
      id: '/api/public/doku/notification'
      path: '/api/public/doku/notification'
      fullPath: '/api/public/doku/notification'
      preLoaderRoute: typeof ApiPublicDokuNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud/upload': {
      id: '/api/public/cloud/upload'
      path: '/api/public/cloud/upload'
      fullPath: '/api/public/cloud/upload'
      preLoaderRoute: typeof ApiPublicCloudUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud/file/$id': {
      id: '/api/public/cloud/file/$id'
      path: '/api/public/cloud/file/$id'
      fullPath: '/api/public/cloud/file/$id'
      preLoaderRoute: typeof ApiPublicCloudFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminActivityLogRoute: typeof AdminActivityLogRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTokenBankRoute: typeof AdminTokenBankRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminActivityLogRoute: AdminActivityLogRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTokenBankRoute: AdminTokenBankRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiInfluencerRouteChildren {
  AiInfluencerAnalyticsRoute: typeof AiInfluencerAnalyticsRoute
  AiInfluencerBrainRoute: typeof AiInfluencerBrainRoute
  AiInfluencerCharacterRoute: typeof AiInfluencerCharacterRoute
  AiInfluencerLibraryRoute: typeof AiInfluencerLibraryRoute
  AiInfluencerPlannerRoute: typeof AiInfluencerPlannerRoute
  AiInfluencerPublisherRoute: typeof AiInfluencerPublisherRoute
  AiInfluencerIndexRoute: typeof AiInfluencerIndexRoute
}

const AiInfluencerRouteChildren: AiInfluencerRouteChildren = {
  AiInfluencerAnalyticsRoute: AiInfluencerAnalyticsRoute,
  AiInfluencerBrainRoute: AiInfluencerBrainRoute,
  AiInfluencerCharacterRoute: AiInfluencerCharacterRoute,
  AiInfluencerLibraryRoute: AiInfluencerLibraryRoute,
  AiInfluencerPlannerRoute: AiInfluencerPlannerRoute,
  AiInfluencerPublisherRoute: AiInfluencerPublisherRoute,
  AiInfluencerIndexRoute: AiInfluencerIndexRoute,
}

const AiInfluencerRouteWithChildren = AiInfluencerRoute._addFileChildren(
  AiInfluencerRouteChildren,
)

interface MixingRouteChildren {
  MixingClipperRoute: typeof MixingClipperRoute
  MixingDubbingRoute: typeof MixingDubbingRoute
}

const MixingRouteChildren: MixingRouteChildren = {
  MixingClipperRoute: MixingClipperRoute,
  MixingDubbingRoute: MixingDubbingRoute,
}

const MixingRouteWithChildren =
  MixingRoute._addFileChildren(MixingRouteChildren)

interface ReffEditRouteChildren {
  ReffEditHistoryRoute: typeof ReffEditHistoryRoute
  ReffEditImageRoute: typeof ReffEditImageRoute
  ReffEditVideoRoute: typeof ReffEditVideoRoute
}

const ReffEditRouteChildren: ReffEditRouteChildren = {
  ReffEditHistoryRoute: ReffEditHistoryRoute,
  ReffEditImageRoute: ReffEditImageRoute,
  ReffEditVideoRoute: ReffEditVideoRoute,
}

const ReffEditRouteWithChildren = ReffEditRoute._addFileChildren(
  ReffEditRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiInfluencerRoute: AiInfluencerRouteWithChildren,
  MixingRoute: MixingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReffEditRoute: ReffEditRouteWithChildren,
  ApiProxyImageRoute: ApiProxyImageRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevWeavyNodeInspectRoute: DevWeavyNodeInspectRoute,
  DevWeavyTestRoute: DevWeavyTestRoute,
  GenerateBulkFashionRoute: GenerateBulkFashionRoute,
  GenerateFramiaRoute: GenerateFramiaRoute,
  GenerateImageToVideoRoute: GenerateImageToVideoRoute,
  GenerateLeonardoRoute: GenerateLeonardoRoute,
  GenerateMotionRoute: GenerateMotionRoute,
  GenerateNaratifRoute: GenerateNaratifRoute,
  GenerateStoryboardRoute: GenerateStoryboardRoute,
  GenerateTextToVideoRoute: GenerateTextToVideoRoute,
  GenerateUpscalerRoute: GenerateUpscalerRoute,
  ManageAccountsRoute: ManageAccountsRoute,
  ManageRoutingRoute: ManageRoutingRoute,
  ManageTokensRoute: ManageTokensRoute,
  SystemAnalyticRoute: SystemAnalyticRoute,
  SystemCloudRoute: SystemCloudRoute,
  SystemHelpRoute: SystemHelpRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  ApiPublicBacksoundSearchRoute: ApiPublicBacksoundSearchRoute,
  ApiPublicClipperBrainRoute: ApiPublicClipperBrainRoute,
  ApiPublicCreativeBrainRoute: ApiPublicCreativeBrainRoute,
  ApiPublicDubbingBrainRoute: ApiPublicDubbingBrainRoute,
  ApiPublicElevenlabsTtsRoute: ApiPublicElevenlabsTtsRoute,
  ApiPublicElevenlabsValidateRoute: ApiPublicElevenlabsValidateRoute,
  ApiPublicFfmpegCdnRoute: ApiPublicFfmpegCdnRoute,
  ApiPublicFireflyRoute: ApiPublicFireflyRoute,
  ApiPublicFramiaRoute: ApiPublicFramiaRoute,
  ApiPublicLeonardoRoute: ApiPublicLeonardoRoute,
  ApiPublicLeonardoCognitoRoute: ApiPublicLeonardoCognitoRoute,
  ApiPublicMagnificRoute: ApiPublicMagnificRoute,
  ApiPublicNaratifBrainRoute: ApiPublicNaratifBrainRoute,
  ApiPublicNewsFeedRoute: ApiPublicNewsFeedRoute,
  ApiPublicProxyImageRoute: ApiPublicProxyImageRoute,
  ApiPublicRoboneoRoute: ApiPublicRoboneoRoute,
  ApiPublicRoboneoMembershipRoute: ApiPublicRoboneoMembershipRoute,
  ApiPublicScrapeArticleRoute: ApiPublicScrapeArticleRoute,
  ApiPublicScrapeProductRoute: ApiPublicScrapeProductRoute,
  ApiPublicStoryboardBrainRoute: ApiPublicStoryboardBrainRoute,
  ApiPublicUploadCatboxRoute: ApiPublicUploadCatboxRoute,
  ApiPublicValidateMediaRoute: ApiPublicValidateMediaRoute,
  ApiRouterBrainAnalyzeRoute: ApiRouterBrainAnalyzeRoute,
  ApiRouterChatRoute: ApiRouterChatRoute,
  ApiRouterImageRoute: ApiRouterImageRoute,
  ApiRouterPlanWeeklyRoute: ApiRouterPlanWeeklyRoute,
  ApiRouterRenderRoute: ApiRouterRenderRoute,
  ApiRouterRenderCloudRoute: ApiRouterRenderCloudRoute,
  ApiRouterSttRoute: ApiRouterSttRoute,
  ApiRouterSubtitleRoute: ApiRouterSubtitleRoute,
  ApiRouterVoiceRoute: ApiRouterVoiceRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
  ApiPublicCloudUploadRoute: ApiPublicCloudUploadRoute,
  ApiPublicDokuNotificationRoute: ApiPublicDokuNotificationRoute,
  ApiPublicExtensionLoginRoute: ApiPublicExtensionLoginRoute,
  ApiPublicExtensionPushTokenRoute: ApiPublicExtensionPushTokenRoute,
  ApiPublicExtensionRefreshRoute: ApiPublicExtensionRefreshRoute,
  ApiPublicGoogleDriveCallbackRoute: ApiPublicGoogleDriveCallbackRoute,
  ApiPublicMidtransNotificationRoute: ApiPublicMidtransNotificationRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
  ApiPublicCloudFileIdRoute: ApiPublicCloudFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
